branches:
  only:
    - master
    - develop
    
hosts:
  api.nuget.org: 93.184.221.200

init:
  - git config --global core.autocrlf true

build_script:
  - ps: .\build.ps1 -Target "AppVeyor"
   
test: off

cache:
- src\packages -> src\**\packages.config
- tools -> tools\packages.config

image: Visual Studio 2017
  
on_failure:
  - ps: Update-AppveyorBuild -Version "$($env:appveyor_build_version)-$(Get-Date -format HHmmss)-failed"
